### ISSUE TITLE
Chosen hash function is colliding

### ISSUE THREAD

**Issue by X-Ryl669** [jkent/esp32-espfs#29]
Currently chosen hash function is colliding. In effect, any char X followed by Y so that Y = X+33 gives the same result as X+1 followed by X.
And since a path is very likely to have successive char with a distance of 33 between them, this is going to happen frequently. 
For example, "2S" gives the same hash as "32"

Replacing:
```cpp
static uint32_t hash_path(const char *path)
{
    uint32_t hash = 5381;
    const uint8_t *p = (uint8_t *)path;

    while (*p) {
        /* hash = hash * 33 + *p */
        hash = (hash << 5) + hash + *p;
        p++;
    }

    return hash;
}
```
by
```cpp
static uint32_t hash_path(const char *path)
{
    uint32_t hash = 5381;
    const uint8_t *p = (uint8_t *)path;

    while (*p) {
        /* hash = hash * 257 + *p */
        hash = (hash << 8) + hash + *p;
        p++;
    }

    return hash;
}
```
will solve this issue since there is no char that's 257 higher than another.

**Comment by jkent** [comment]
Thank you!  I'm not sure where I pulled the original hashing function from, but this does make way more sense.  Would you mind updating your pull request and increment ESPFS_VERSION_MAJOR?

**Comment by jkent** [comment]
Resolved, thank you again.
