### ISSUE TITLE
CONFIG parameter broken in target_add_frogfs (next branch)

### ISSUE THREAD

**Issue by valkuc** [jkent/esp32-espfs#48]
Hi. I'm trying to use `target_add_frogfs` with `CONFIG` parameter but it results in wrong invocation of `mkfrogfs.py` as it is necessary to pass additional `--config` cmd line argument that is missing in `functions.cmake` file. As result the next error is generated in build output:

```
usage: mkfrogfs.py [-h] [--config CONFIG] ROOT OUTPUT
mkfrogfs.py: error: unrecognized arguments: E:/Espressif/workspace/httpd/build/frogfs.bin
```

A quick fix is to modify line 45 in functions.cmake to look like:
```
COMMAND ${CMAKE_COMMAND} -E env CMAKEFILES_DIR=${BUILD_DIR}/CMakeFiles ${Python3_VENV_EXECUTABLE} ${frogfs_DIR}/tools/mkfrogfs.py ${directories} --config ${ARG_CONFIG} ${path} ${output}.bin
```
(pay attention --config added here)

But then it will break compilation without CONFIG argument.

**Comment by jkent** [comment]
Should be good to go!  Thanks for catching this.
