### ISSUE TITLE
suggestion: use project_include.cmake to automatically import frogfs functions

### ISSUE THREAD

**Issue by igrr** [jkent/esp32-espfs#54]
For IDF-specific CMake projects, this part of frogfs usage:
```
include(components/frogfs/cmake/functions.cmake)   # <<<
target_add_frogfs(my_project.elf html NAME frogfs CONFIG frogfs.yaml)
```
could be simplified by adding a `project_include.cmake` file into the component root directory. IDF build system includes `project_include.cmake` files, making the functions defined there available in component and project CMakeLists files.

Here are some examples:
- spiffs adds its `spiffs_create_partition_image` function [this way](https://github.com/espressif/esp-idf/blob/8fc8f3f47997aadba21facabc66004c1d22de181/components/spiffs/project_include.cmake)
- and it is used in [the example](https://github.com/espressif/esp-idf/blob/8fc8f3f47997aadba21facabc66004c1d22de181/examples/storage/spiffsgen/main/CMakeLists.txt#L8) later

(Generic CMake projects can continue using `include(...)`, as this is more idiomatic in CMake. For IDF-specific projects, though, making the function available immediately after adding the component to the build is more common.)

**Comment by jkent** [comment]
The README.md you referenced is out of date.  Major development has been occurring in the `next` branch.  However I have restructured this project as you have suggested.  Thanks @igrr
