### ISSUE TITLE
How to get espfs image size?

### ISSUE THREAD

**Issue by mharizanov** [jkent/esp32-espfs#8]
I need to know the espfs image size, so I can calculate MD5 on it and check if updating it over OTA was successful.
Is there a way to get the espfs image size other than traversing through the included files?

Cheers

**Comment by jkent** [comment]
Yes, at the moment you can use `image_espfs_size` or `image_espfs_end - image_espfs_start` to get the size using `espfs_image.h`.  The interface will be changing in the future (wip branch) to `espfs_image_bin_len` because xxd is being used to include espfs binary.

Hope that helps!

**Comment by jkent** [comment]
I just re-read your comment and I realized you want to OTA the espfs binary separate from the firmware binary?  Is that correct?  There currently isn't a provision for that, but it could be implemented.

**Comment by mharizanov** [comment]
Yes, exactly. It is flashed on a separate partition and not embedded into the binary, so your original proposal won't work for this use case. 
OK, I'll just go for iterating and summing up the file sizes.
Thank you!

**Comment by jkent** [comment]
I'm going to create a new issue, so this gets first class support.  I never really thought about having espfs OTA'd separate from the application binary.
